title: Owl's Nest Creations
description: >-
  Owl's Nest Creations turns equations into experiences you can hold
  in one hand. Each of our games is designed with physics at its heart.
  Let's play!
url: "https://owlsnestcreations.com"
email: hello@owlsnestcreations.com

collections:
  games:
    output: true
    permalink: /games/:name/

defaults:
  - scope:
      path: ""
      type: games
    values:
      layout: game

sass:
  style: compressed
  quiet_deps: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
